// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_fee_and_finish`, `btc_params`, `clear_scan_marks`, `enclave_prevout_to_txout`, `enclave_prevouts_to_txouts`, `enclave_sighash_inner`, `err`, `esplora_client`, `hexbytes`, `last_scan`, `mark_scanned`, `openamp_keypair`, `parse_openamp_tx`, `rerr`, `scan_into`, `scanned_recently`, `tohex`, `with_synced_wollet`, `wollet_cache`

/// The active Sequentia network's identifier, e.g. `"sequentia-testnet"`.
String networkName() => RustLib.instance.api.crateApiNetworkName();

/// Point wallet persistence at the app's writable directory. Call once at
/// startup, before any sync, so cold starts resume scanned state from disk
/// instead of re-scanning the whole wallet.
void setDataDir({required String path}) =>
    RustLib.instance.api.crateApiSetDataDir(path: path);

/// Set the `Authorization` header for a node behind HTTP auth (a bearer token or
/// basic-auth credentials). Pass an empty string to clear it. Applied to every
/// Esplora request; call whenever the node or its credentials change.
void setAuthHeader({required String value}) =>
    RustLib.instance.api.crateApiSetAuthHeader(value: value);

/// Generate a fresh 12-word BIP39 recovery phrase.
Future<String> generateMnemonic() =>
    RustLib.instance.api.crateApiGenerateMnemonic();

/// The default (non-confidential, Bitcoin-format `tb1…`) receive address for a
/// recovery phrase, at index 0. The same address also receives on Bitcoin
/// testnet4 — one address, both chains.
Future<String> receiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiReceiveAddress(mnemonic: mnemonic);

/// The opt-in confidential ("private", blech32 `tsqb…`) receive address at
/// index 0. NOT Bitcoin-compatible (it embeds a blinding key).
Future<String> confidentialReceiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiConfidentialReceiveAddress(mnemonic: mnemonic);

/// The wallet's CT output descriptor for a recovery phrase.
Future<String> descriptorFromMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiDescriptorFromMnemonic(mnemonic: mnemonic);

/// Validate a BIP39 recovery phrase (import flow). Throws on an invalid phrase.
Future<void> validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiValidateMnemonic(mnemonic: mnemonic);

/// Receive address at `index`: non-confidential `tb1…` (default) or the opt-in
/// confidential `tsqb…` form. Returns the address + the index it used.
Future<AddressInfo> receiveAddressAt({
  required String mnemonic,
  required int index,
  required bool confidential,
}) => RustLib.instance.api.crateApiReceiveAddressAt(
  mnemonic: mnemonic,
  index: index,
  confidential: confidential,
);

/// Scan the wallet's Bitcoin (testnet4) keychain; returns the balance and the
/// cycling indices. `t4_api` is the testnet4 esplora base (e.g. `<node>/testnet4/api`).
Future<BtcBalance> btcSync({required String mnemonic, required String t4Api}) =>
    RustLib.instance.api.crateApiBtcSync(mnemonic: mnemonic, t4Api: t4Api);

/// Build + sign (but DON'T broadcast) a Bitcoin testnet4 payment of `amount_sats`
/// to `address`, at `fee_rate` sat/vB. Show the returned fee/vsize for review,
/// then [`btc_broadcast`] the hex to send.
Future<BtcTx> btcPrepare({
  required String mnemonic,
  required String t4Api,
  required String address,
  required BigInt amountSats,
  required double feeRate,
}) => RustLib.instance.api.crateApiBtcPrepare(
  mnemonic: mnemonic,
  t4Api: t4Api,
  address: address,
  amountSats: amountSats,
  feeRate: feeRate,
);

/// Broadcast a prepared Bitcoin testnet4 transaction hex; returns the txid.
Future<String> btcBroadcast({required String t4Api, required String txHex}) =>
    RustLib.instance.api.crateApiBtcBroadcast(t4Api: t4Api, txHex: txHex);

/// Build the taker (proposer) half of a SeqDEX same-chain swap. `asset_*` are
/// display hex; amounts are atoms. Open fee market: `fee_amount == 0` ⇒ the maker
/// funds the network fee in `asset_r` (default); `fee_amount > 0` ⇒ the taker
/// funds it in `fee_asset` (any held, fee-eligible asset except `asset_r`),
/// adding a fee input + explicit fee output. `fee_rate` is `fee_asset`'s
/// published rate (atoms per 1e8 native), used only for the dust threshold.
/// Returns the swap id + the SwapRequest JSON to hand to the daemon's ProposeTrade.
Future<SeqdexSwapRequestOut> seqdexBuildSwapRequest({
  required String mnemonic,
  required String esploraUrl,
  required String assetP,
  required BigInt amountP,
  required String assetR,
  required BigInt amountR,
  required String feeAsset,
  required BigInt feeAmount,
  required BigInt feeRate,
}) => RustLib.instance.api.crateApiSeqdexBuildSwapRequest(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  assetP: assetP,
  amountP: amountP,
  assetR: assetR,
  amountR: amountR,
  feeAsset: feeAsset,
  feeAmount: feeAmount,
  feeRate: feeRate,
);

/// Sign the maker's SwapAccept PSET (base64) and return the stripped, signed PSET
/// (base64) for /v1/trade/complete. Runs through the synced wallet so add_details
/// can recognise the taker's own input by its scriptPubKey (else it's skipped and
/// left unsigned). The maker's signatures on its inputs are preserved.
Future<String> seqdexSignAccept({
  required String mnemonic,
  required String esploraUrl,
  required String acceptPset,
}) => RustLib.instance.api.crateApiSeqdexSignAccept(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  acceptPset: acceptPset,
);

/// Generate the swap preimage + hashlock.
Future<XchainSecret> xchainNewSecret() =>
    RustLib.instance.api.crateApiXchainNewSecret();

/// Alice's SEQ-leg claim pubkey (the HTLC claim key; secret stays in the core).
Future<String> xchainSeqClaimPubkey({required String mnemonic}) =>
    RustLib.instance.api.crateApiXchainSeqClaimPubkey(mnemonic: mnemonic);

/// Alice's BTC-leg refund pubkey.
Future<String> xchainBtcRefundPubkey({required String mnemonic}) =>
    RustLib.instance.api.crateApiXchainBtcRefundPubkey(mnemonic: mnemonic);

/// Build the BTC HTLC the wallet will fund: redeemScript + P2SH address/spk.
Future<BtcHtlcInfo> xchainBtcHtlc({
  required String hashHex,
  required String claimPubHex,
  required String refundPubHex,
  required int locktime,
}) => RustLib.instance.api.crateApiXchainBtcHtlc(
  hashHex: hashHex,
  claimPubHex: claimPubHex,
  refundPubHex: refundPubHex,
  locktime: locktime,
);

/// The SEQ-leg redeemScript Alice rebuilds, as hex — compare it to the daemon's
/// reported `seqLeg.redeemScript` (value-binding) before trusting the leg.
Future<String> xchainSeqRedeemScript({
  required String mnemonic,
  required String hashHex,
  required String makerSeqRefundPubHex,
  required int seqLocktime,
}) => RustLib.instance.api.crateApiXchainSeqRedeemScript(
  mnemonic: mnemonic,
  hashHex: hashHex,
  makerSeqRefundPubHex: makerSeqRefundPubHex,
  seqLocktime: seqLocktime,
);

/// Locate the BTC HTLC funding output by its P2SH scriptPubKey on testnet4.
Future<BtcFunding> xchainFindBtcFunding({
  required String t4Api,
  required String txid,
  required String p2ShSpkHex,
}) => RustLib.instance.api.crateApiXchainFindBtcFunding(
  t4Api: t4Api,
  txid: txid,
  p2ShSpkHex: p2ShSpkHex,
);

/// THE REVEAL GATE. ok == true means it is safe to broadcast the SEQ claim:
/// the SEQ leg's Bitcoin anchor >= the BTC funding height, anchorstatus "ok",
/// and the anchor is >= `min_depth` Bitcoin-confs deep (default D = 1).
Future<AnchorEvidence> xchainVerifySeqLegSafe({
  required String seqEsplora,
  required String seqBlockHash,
  required PlatformInt64 btcLegHeight,
  required String t4Api,
  required PlatformInt64 minDepth,
}) => RustLib.instance.api.crateApiXchainVerifySeqLegSafe(
  seqEsplora: seqEsplora,
  seqBlockHash: seqBlockHash,
  btcLegHeight: btcLegHeight,
  t4Api: t4Api,
  minDepth: minDepth,
);

/// Build the SEQ claim tx (reveals the preimage). Only call after the reveal gate
/// passes. Returns the raw Elements tx hex to [`xchain_seq_broadcast`].
Future<String> xchainSeqClaim({
  required String mnemonic,
  required String seqTxid,
  required int seqVout,
  required BigInt seqAmount,
  required String seqAssetId,
  required String destAddress,
  required String hashHex,
  required String makerSeqRefundPubHex,
  required int seqLocktime,
  required BigInt fee,
  required String preimageHex,
}) => RustLib.instance.api.crateApiXchainSeqClaim(
  mnemonic: mnemonic,
  seqTxid: seqTxid,
  seqVout: seqVout,
  seqAmount: seqAmount,
  seqAssetId: seqAssetId,
  destAddress: destAddress,
  hashHex: hashHex,
  makerSeqRefundPubHex: makerSeqRefundPubHex,
  seqLocktime: seqLocktime,
  fee: fee,
  preimageHex: preimageHex,
);

/// Broadcast a raw SEQ (Elements) tx hex; returns the txid.
Future<String> xchainSeqBroadcast({
  required String seqEsplora,
  required String txHex,
}) => RustLib.instance.api.crateApiXchainSeqBroadcast(
  seqEsplora: seqEsplora,
  txHex: txHex,
);

/// Build the BTC HTLC refund (CLTV/ELSE branch), valid once the chain tip reaches
/// `locktime`. Returns raw tx hex for [`btc_broadcast`].
Future<String> xchainBtcRefund({
  required String mnemonic,
  required String btcTxid,
  required int btcVout,
  required BigInt btcAmountSats,
  required String destAddress,
  required BigInt feeSats,
  required String redeemScriptHex,
  required int locktime,
}) => RustLib.instance.api.crateApiXchainBtcRefund(
  mnemonic: mnemonic,
  btcTxid: btcTxid,
  btcVout: btcVout,
  btcAmountSats: btcAmountSats,
  destAddress: destAddress,
  feeSats: feeSats,
  redeemScriptHex: redeemScriptHex,
  locktime: locktime,
);

/// Full-scan the wallet against `esplora_url`, apply the update, and return the
/// chain tip, per-asset balances, and the next unused receive index. Runs on an
/// FRB worker thread (off the UI thread).
Future<WalletSync> syncWallet({
  required String mnemonic,
  required String esploraUrl,
}) => RustLib.instance.api.crateApiSyncWallet(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
);

/// Validate a recipient address is a well-formed **Sequentia** address (rejects
/// foreign-network addresses).
Future<void> validateAddress({required String address}) =>
    RustLib.instance.api.crateApiValidateAddress(address: address);

/// Build an UNSIGNED send PSET (base64). Syncs first so the wallet has utxos.
/// `fee_asset` pays the fee in any accepted asset at the EXACT published rate
/// (never fabricated); `fee_rate_sat_kvb` None = builder default. RBF is on by
/// default (so a stuck tx can be bump/CPFP-rescued later).
Future<String> buildSendTx({
  required String mnemonic,
  required String esploraUrl,
  required List<Recipient> recipients,
  double? feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildSendTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  recipients: recipients,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// Sign a PSET with the software signer (mnemonic read transiently, never
/// cached). Returns the signed PSET as base64.
Future<String> signPset({required String mnemonic, required String pset}) =>
    RustLib.instance.api.crateApiSignPset(mnemonic: mnemonic, pset: pset);

/// Finalize a signed PSET into a transaction and broadcast it. Returns the txid.
Future<String> finalizeAndBroadcast({
  required String mnemonic,
  required String esploraUrl,
  required String pset,
}) => RustLib.instance.api.crateApiFinalizeAndBroadcast(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  pset: pset,
);

/// Sync and return the wallet's transaction history (net signed per-asset deltas
/// per tx). Ordering is left to the UI.
Future<List<TxRow>> walletTransactions({
  required String mnemonic,
  required String esploraUrl,
}) => RustLib.instance.api.crateApiWalletTransactions(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
);

/// Forget any cached wallet state (called when the wallet is removed).
Future<void> clearWalletCache() =>
    RustLib.instance.api.crateApiClearWalletCache();

/// Read the network fee out of a built (unsigned) PSET so the review can show an
/// estimate. For an any-asset-fee tx this is the chosen fee asset, not tSEQ.
Future<PsetFee> psetFee({required String pset}) =>
    RustLib.instance.api.crateApiPsetFee(pset: pset);

/// RBF fee-bump: re-send the SAME payment at a higher fee (optionally in another
/// asset). The replacement's reference (rfa) fee must exceed the original's.
Future<String> buildRbfBumpTx({
  required String mnemonic,
  required String esploraUrl,
  required String txid,
  required double feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildRbfBumpTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  txid: txid,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// RBF replace: same inputs, brand-new recipients — to correct a still-pending
/// payment's address/asset/amount.
Future<String> buildRbfReplaceTx({
  required String mnemonic,
  required String esploraUrl,
  required String txid,
  required List<Recipient> newRecipients,
  required double feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildRbfReplaceTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  txid: txid,
  newRecipients: newRecipients,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// CPFP: a child that spends the parent's unconfirmed wallet output and pays a
/// high fee (in any accepted asset) to lift the {parent, child} package.
Future<String> buildCpfpTx({
  required String mnemonic,
  required String esploraUrl,
  required String parentTxid,
  required double feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildCpfpTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  parentTxid: parentTxid,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// A conservative child fee rate (sat/kvb) that lifts the {parent, child}
/// package to `target_feerate`.
Future<double> cpfpSuggestedFeerate({
  required String mnemonic,
  required String esploraUrl,
  required String parentTxid,
  required double targetFeerate,
}) => RustLib.instance.api.crateApiCpfpSuggestedFeerate(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  parentTxid: parentTxid,
  targetFeerate: targetFeerate,
);

/// Issue a brand-new asset: mint `asset_sats` of it plus `token_sats` reissuance
/// tokens, both to this wallet. The new asset's id appears after the tx
/// confirms and the wallet re-syncs.
Future<String> buildIssueTx({
  required String mnemonic,
  required String esploraUrl,
  required BigInt assetSats,
  required BigInt tokenSats,
  double? feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildIssueTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  assetSats: assetSats,
  tokenSats: tokenSats,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// Reissue more of an existing asset (needs its reissuance token in this wallet).
Future<String> buildReissueTx({
  required String mnemonic,
  required String esploraUrl,
  required String assetId,
  required BigInt satoshi,
  double? feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildReissueTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  assetId: assetId,
  satoshi: satoshi,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// Permanently destroy `satoshi` atoms of an asset.
Future<String> buildBurnTx({
  required String mnemonic,
  required String esploraUrl,
  required String assetId,
  required BigInt satoshi,
  double? feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildBurnTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  assetId: assetId,
  satoshi: satoshi,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// The 33-byte staker public key (compressed hex) at m/2/0 — the key a stake is
/// bonded to (the wallet controls the matching private key to later unbond).
Future<String> stakerPublicKey({required String mnemonic}) =>
    RustLib.instance.api.crateApiStakerPublicKey(mnemonic: mnemonic);

/// Bond `satoshi` atoms of tSEQ into the canonical CSV-locked staking script for
/// `staker_pubkey` (33-byte hex). Enforces the 40,000-tSEQ minimum. The output
/// is non-confidential (only explicit stake confers weight).
Future<String> buildStakeTx({
  required String mnemonic,
  required String esploraUrl,
  required String stakerPubkey,
  required int csv,
  required BigInt satoshi,
  double? feeRateSatKvb,
  FeeAsset? feeAsset,
}) => RustLib.instance.api.crateApiBuildStakeTx(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
  stakerPubkey: stakerPubkey,
  csv: csv,
  satoshi: satoshi,
  feeRateSatKvb: feeRateSatKvb,
  feeAsset: feeAsset,
);

/// The 32-byte x-only public key (BIP340) at m/5/0, as 64-char hex — the key an
/// OpenAMP enclave user registers under (`POST /v1/users {pubkeys:[..]}`).
String openampXonlyPubkey({required String mnemonic}) =>
    RustLib.instance.api.crateApiOpenampXonlyPubkey(mnemonic: mnemonic);

/// Schnorr-sign a 32-byte enclave transfer sighash (64-char hex) under the same
/// dedicated m/5/0 key, returning the 64-byte (128-char hex) BIP340 signature.
/// Verifies under the key from [`openamp_xonly_pubkey`].
String openampSignSighash({
  required String mnemonic,
  required String sighashHex,
}) => RustLib.instance.api.crateApiOpenampSignSighash(
  mnemonic: mnemonic,
  sighashHex: sighashHex,
);

/// Compute an OpenAMP AID locally from a set of 64-hex x-only pubkeys, exactly
/// matching Go `store.AID`: `hex(first 20 bytes of sha256("openamp-aid-v1" ||
/// pubkeys lowercased, sorted lexicographically, concatenated as UTF-8))`. The
/// wallet MUST call this and assert equality with the server's AID (spec 1.3);
/// a mismatch means the server registered a different or additional key.
String openampComputeAid({required List<String> pubkeys}) =>
    RustLib.instance.api.crateApiOpenampComputeAid(pubkeys: pubkeys);

/// The Sequentia network genesis block hash (hex), the taproot sighash domain
/// separator the wallet must pass to [`enclave_sighash`]. Resolved from the
/// active network so Dart never hardcodes it.
String sequentiaGenesisHash() =>
    RustLib.instance.api.crateApiSequentiaGenesisHash();

/// Recompute the enclave-spend sighash the wallet must sign (SWK-6, spec 0.4(3)).
///
/// - `tx_hex`: the FULL unsigned transaction the enclave asked the wallet to sign.
/// - `input_index`: which input this enclave spend is.
/// - `prevouts`: `{asset, value, script}` for EVERY input, aligned by index
///   (taproot SIGHASH_DEFAULT commits to all prevout amounts + scripts).
/// - `leaf_script_hex`: the enclave transfer leaf.
/// - `control_block_hex`: the transfer-leaf control block (first byte = leaf
///   version `0xc4` with the parity bit).
/// - `genesis_hex`: the network genesis block hash (from [`sequentia_genesis_hash`]).
///
/// Returns the 32-byte sighash as hex. The wallet MUST sign THIS value and refuse
/// if it differs from the server's `to_sign` digest.
String enclaveSighash({
  required String txHex,
  required int inputIndex,
  required List<EnclavePrevout> prevouts,
  required String leafScriptHex,
  required String controlBlockHex,
  required String genesisHex,
}) => RustLib.instance.api.crateApiEnclaveSighash(
  txHex: txHex,
  inputIndex: inputIndex,
  prevouts: prevouts,
  leafScriptHex: leafScriptHex,
  controlBlockHex: controlBlockHex,
  genesisHex: genesisHex,
);

/// Decode a candidate enclave-spend transaction into the effects a wallet must
/// display before signing (SWK-6, spec 0.4(3)). `my_scripts` is the set of MY
/// enclave scriptPubKeys (hex); a prevout or output matching one is flagged
/// `mine`. `prevouts` aligns with the transaction inputs; pass an empty list to
/// only enumerate each input's outpoint (txid/vout/index).
EnclaveSpendEffects decodeEnclaveSpend({
  required String txHex,
  required List<EnclavePrevout> prevouts,
  required List<String> myScripts,
}) => RustLib.instance.api.crateApiDecodeEnclaveSpend(
  txHex: txHex,
  prevouts: prevouts,
  myScripts: myScripts,
);

/// A receive address together with the derivation index it came from.
class AddressInfo {
  final String address;
  final int index;

  const AddressInfo({required this.address, required this.index});

  @override
  int get hashCode => address.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          index == other.index;
}

/// The reveal-gate verdict + the evidence behind it (all from the wallet's own
/// nodes). `ok` true means it is safe to reveal the preimage.
class AnchorEvidence {
  final PlatformInt64 seqAnchorHeight;
  final PlatformInt64 btcLegHeight;
  final PlatformInt64 btcTip;
  final String anchorStatus;
  final PlatformInt64 depth;
  final bool ok;

  const AnchorEvidence({
    required this.seqAnchorHeight,
    required this.btcLegHeight,
    required this.btcTip,
    required this.anchorStatus,
    required this.depth,
    required this.ok,
  });

  @override
  int get hashCode =>
      seqAnchorHeight.hashCode ^
      btcLegHeight.hashCode ^
      btcTip.hashCode ^
      anchorStatus.hashCode ^
      depth.hashCode ^
      ok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnchorEvidence &&
          runtimeType == other.runtimeType &&
          seqAnchorHeight == other.seqAnchorHeight &&
          btcLegHeight == other.btcLegHeight &&
          btcTip == other.btcTip &&
          anchorStatus == other.anchorStatus &&
          depth == other.depth &&
          ok == other.ok;
}

/// A per-asset balance: the asset id (hex) and the amount in atoms (a string to
/// avoid any integer-precision loss across the FFI boundary).
class AssetBalance {
  final String assetId;
  final String atoms;

  const AssetBalance({required this.assetId, required this.atoms});

  @override
  int get hashCode => assetId.hashCode ^ atoms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetBalance &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          atoms == other.atoms;
}

/// A signed per-asset delta on a transaction (atoms as a string; may be negative).
class AssetDelta {
  final String assetId;
  final String atoms;

  const AssetDelta({required this.assetId, required this.atoms});

  @override
  int get hashCode => assetId.hashCode ^ atoms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetDelta &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          atoms == other.atoms;
}

/// Result of scanning the Bitcoin keychain: the balance (sats, as a string for
/// FFI precision-safety) plus the next-unused indices for cross-chain address
/// cycling (the shared receive address advances past use on EITHER chain).
class BtcBalance {
  final String balanceSats;
  final int externalNext;
  final int changeNext;

  const BtcBalance({
    required this.balanceSats,
    required this.externalNext,
    required this.changeNext,
  });

  @override
  int get hashCode =>
      balanceSats.hashCode ^ externalNext.hashCode ^ changeNext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BtcBalance &&
          runtimeType == other.runtimeType &&
          balanceSats == other.balanceSats &&
          externalNext == other.externalNext &&
          changeNext == other.changeNext;
}

/// A located BTC HTLC funding output (value as a string for FFI precision).
class BtcFunding {
  final int vout;
  final String valueSats;
  final PlatformInt64 height;
  final PlatformInt64 confirmations;

  const BtcFunding({
    required this.vout,
    required this.valueSats,
    required this.height,
    required this.confirmations,
  });

  @override
  int get hashCode =>
      vout.hashCode ^
      valueSats.hashCode ^
      height.hashCode ^
      confirmations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BtcFunding &&
          runtimeType == other.runtimeType &&
          vout == other.vout &&
          valueSats == other.valueSats &&
          height == other.height &&
          confirmations == other.confirmations;
}

/// The BTC HTLC the wallet funds: the redeemScript + its bare-P2SH address/spk.
class BtcHtlcInfo {
  final String redeemScriptHex;
  final String p2ShAddress;
  final String p2ShSpkHex;

  const BtcHtlcInfo({
    required this.redeemScriptHex,
    required this.p2ShAddress,
    required this.p2ShSpkHex,
  });

  @override
  int get hashCode =>
      redeemScriptHex.hashCode ^ p2ShAddress.hashCode ^ p2ShSpkHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BtcHtlcInfo &&
          runtimeType == other.runtimeType &&
          redeemScriptHex == other.redeemScriptHex &&
          p2ShAddress == other.p2ShAddress &&
          p2ShSpkHex == other.p2ShSpkHex;
}

/// A built + signed (not yet broadcast) Bitcoin transaction, for the review step.
class BtcTx {
  final String hex;
  final String txid;
  final String feeSats;
  final BigInt vsize;
  final int inputs;

  const BtcTx({
    required this.hex,
    required this.txid,
    required this.feeSats,
    required this.vsize,
    required this.inputs,
  });

  @override
  int get hashCode =>
      hex.hashCode ^
      txid.hashCode ^
      feeSats.hashCode ^
      vsize.hashCode ^
      inputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BtcTx &&
          runtimeType == other.runtimeType &&
          hex == other.hex &&
          txid == other.txid &&
          feeSats == other.feeSats &&
          vsize == other.vsize &&
          inputs == other.inputs;
}

/// One decoded input of a candidate enclave spend.
class EnclaveDecodedInput {
  /// Input index in the transaction.
  final int index;

  /// Prevout txid, display hex.
  final String txid;

  /// Prevout vout.
  final int vout;

  /// Prevout asset id (display hex) if the prevout was supplied.
  final String? asset;

  /// Prevout value (atoms) if the prevout was supplied.
  final BigInt? value;

  /// True when the prevout scriptPubKey is one of MY enclave scripts.
  final bool mine;

  const EnclaveDecodedInput({
    required this.index,
    required this.txid,
    required this.vout,
    this.asset,
    this.value,
    required this.mine,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      txid.hashCode ^
      vout.hashCode ^
      asset.hashCode ^
      value.hashCode ^
      mine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnclaveDecodedInput &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          txid == other.txid &&
          vout == other.vout &&
          asset == other.asset &&
          value == other.value &&
          mine == other.mine;
}

/// One decoded output of a candidate enclave spend.
class EnclaveDecodedOutput {
  /// Output index in the transaction.
  final int index;

  /// Explicit asset id (display hex), or `None` if the output is confidential.
  final String? asset;

  /// Explicit value (atoms), or `None` if the output is confidential.
  final BigInt? value;

  /// The output scriptPubKey, hex (empty for the Elements fee output).
  final String script;

  /// True for the explicit Elements fee output (empty scriptPubKey).
  final bool isFee;

  /// True when this output pays one of MY enclave scripts (a receipt to me).
  final bool mine;

  const EnclaveDecodedOutput({
    required this.index,
    this.asset,
    this.value,
    required this.script,
    required this.isFee,
    required this.mine,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      asset.hashCode ^
      value.hashCode ^
      script.hashCode ^
      isFee.hashCode ^
      mine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnclaveDecodedOutput &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          asset == other.asset &&
          value == other.value &&
          script == other.script &&
          isFee == other.isFee &&
          mine == other.mine;
}

/// A transaction prevout as the wallet knows it: explicit asset id, explicit
/// value (atoms), and the scriptPubKey (hex). Restricted-asset transactions are
/// transparent (spec 0.6), so these are always explicit. Aligned 1:1 with the
/// transaction inputs when passed to [`enclave_sighash`] / [`decode_enclave_spend`].
class EnclavePrevout {
  /// The prevout's asset id, display hex.
  final String asset;

  /// The prevout's explicit value, atoms.
  final BigInt value;

  /// The prevout's scriptPubKey, hex.
  final String script;

  const EnclavePrevout({
    required this.asset,
    required this.value,
    required this.script,
  });

  @override
  int get hashCode => asset.hashCode ^ value.hashCode ^ script.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnclavePrevout &&
          runtimeType == other.runtimeType &&
          asset == other.asset &&
          value == other.value &&
          script == other.script;
}

/// The human-readable effects of a candidate enclave spend, shown to the user
/// BEFORE signing (spec 0.4(3)): which of my UTXOs are spent, what each output
/// pays and to whom, and whether anything is confidential (a red flag).
class EnclaveSpendEffects {
  /// The transaction id.
  final String txid;

  /// Every input, with `mine` set for my enclave prevouts.
  final List<EnclaveDecodedInput> inputs;

  /// Every output, with `mine` set for receipts to my enclave scripts.
  final List<EnclaveDecodedOutput> outputs;

  /// Indices of the inputs that spend MY enclave UTXOs.
  final Uint32List myInputsSpent;

  /// True if ANY output is confidential (restricted-asset spends must be fully
  /// transparent, spec 2.4/0.6, so this is an integrity warning).
  final bool anyConfidential;

  const EnclaveSpendEffects({
    required this.txid,
    required this.inputs,
    required this.outputs,
    required this.myInputsSpent,
    required this.anyConfidential,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      inputs.hashCode ^
      outputs.hashCode ^
      myInputsSpent.hashCode ^
      anyConfidential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnclaveSpendEffects &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          inputs == other.inputs &&
          outputs == other.outputs &&
          myInputsSpent == other.myInputsSpent &&
          anyConfidential == other.anyConfidential;
}

/// Pay the fee in any accepted asset at the node's published rate.
class FeeAsset {
  final String assetId;
  final BigInt rate;

  const FeeAsset({required this.assetId, required this.rate});

  @override
  int get hashCode => assetId.hashCode ^ rate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeeAsset &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          rate == other.rate;
}

/// The network fee of a built PSET: the fee output's asset and amount (atoms).
class PsetFee {
  final String assetId;
  final String atoms;

  const PsetFee({required this.assetId, required this.atoms});

  @override
  int get hashCode => assetId.hashCode ^ atoms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PsetFee &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          atoms == other.atoms;
}

/// A send recipient: who, which asset, how many atoms.
class Recipient {
  final String address;
  final String assetId;
  final BigInt satoshi;

  const Recipient({
    required this.address,
    required this.assetId,
    required this.satoshi,
  });

  @override
  int get hashCode => address.hashCode ^ assetId.hashCode ^ satoshi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recipient &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          assetId == other.assetId &&
          satoshi == other.satoshi;
}

/// The taker half of a same-chain swap: the random swap id + the SwapRequest JSON
/// to POST to the daemon's /v1/trade/propose.
class SeqdexSwapRequestOut {
  final String id;
  final String swapRequestJson;

  const SeqdexSwapRequestOut({required this.id, required this.swapRequestJson});

  @override
  int get hashCode => id.hashCode ^ swapRequestJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeqdexSwapRequestOut &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          swapRequestJson == other.swapRequestJson;
}

/// A wallet transaction history row.
class TxRow {
  final String txid;
  final int? height;
  final BigInt? timestamp;

  /// "incoming" | "outgoing" | "issuance" | "reissuance" | "burn" | "redeposit" | "unknown".
  final String kind;
  final BigInt fee;

  /// The asset id (hex) the network fee was paid in. Sequentia's open fee market
  /// lets the fee be ANY accepted asset, not just the policy asset, so the UI
  /// must label the fee with its real asset instead of assuming tSEQ. Falls back
  /// to the policy asset when the tx has no explicit fee output (fee == 0).
  final String feeAsset;
  final List<AssetDelta> deltas;

  const TxRow({
    required this.txid,
    this.height,
    this.timestamp,
    required this.kind,
    required this.fee,
    required this.feeAsset,
    required this.deltas,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      height.hashCode ^
      timestamp.hashCode ^
      kind.hashCode ^
      fee.hashCode ^
      feeAsset.hashCode ^
      deltas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxRow &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          height == other.height &&
          timestamp == other.timestamp &&
          kind == other.kind &&
          fee == other.fee &&
          feeAsset == other.feeAsset &&
          deltas == other.deltas;
}

/// A snapshot of the wallet after a full scan against an esplora backend.
class WalletSync {
  final int tipHeight;
  final String tipHash;
  final List<AssetBalance> balances;
  final int nextIndex;

  const WalletSync({
    required this.tipHeight,
    required this.tipHash,
    required this.balances,
    required this.nextIndex,
  });

  @override
  int get hashCode =>
      tipHeight.hashCode ^
      tipHash.hashCode ^
      balances.hashCode ^
      nextIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSync &&
          runtimeType == other.runtimeType &&
          tipHeight == other.tipHeight &&
          tipHash == other.tipHash &&
          balances == other.balances &&
          nextIndex == other.nextIndex;
}

/// A fresh swap preimage + its SHA256 hashlock. `secret_hex` is NOT HD-derivable;
/// the caller MUST persist it before locking any BTC.
class XchainSecret {
  final String secretHex;
  final String hashHex;

  const XchainSecret({required this.secretHex, required this.hashHex});

  @override
  int get hashCode => secretHex.hashCode ^ hashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is XchainSecret &&
          runtimeType == other.runtimeType &&
          secretHex == other.secretHex &&
          hashHex == other.hashHex;
}
