// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`

/// The active Sequentia network's identifier, e.g. `"sequentia-testnet"`.
String networkName() => RustLib.instance.api.crateApiNetworkName();

/// Generate a fresh 12-word BIP39 recovery phrase.
Future<String> generateMnemonic() =>
    RustLib.instance.api.crateApiGenerateMnemonic();

/// The default (non-confidential, Bitcoin-format `tb1…`) receive address for a
/// recovery phrase, at index 0. The same address also receives on Bitcoin
/// testnet4 — one address, both chains.
Future<String> receiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiReceiveAddress(mnemonic: mnemonic);

/// The opt-in confidential ("private", blech32 `tsqb…`) receive address at
/// index 0. NOT Bitcoin-compatible (it embeds a blinding key).
Future<String> confidentialReceiveAddress({required String mnemonic}) =>
    RustLib.instance.api.crateApiConfidentialReceiveAddress(mnemonic: mnemonic);

/// The wallet's CT output descriptor for a recovery phrase.
Future<String> descriptorFromMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiDescriptorFromMnemonic(mnemonic: mnemonic);

/// Validate a BIP39 recovery phrase (import flow). Throws on an invalid phrase.
Future<void> validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiValidateMnemonic(mnemonic: mnemonic);

/// Receive address at `index`: non-confidential `tb1…` (default) or the opt-in
/// confidential `tsqb…` form. Returns the address + the index it used.
Future<AddressInfo> receiveAddressAt({
  required String mnemonic,
  required int index,
  required bool confidential,
}) => RustLib.instance.api.crateApiReceiveAddressAt(
  mnemonic: mnemonic,
  index: index,
  confidential: confidential,
);

/// Full-scan the wallet against `esplora_url`, apply the update, and return the
/// chain tip, per-asset balances, and the next unused receive index. Runs on an
/// FRB worker thread (off the UI thread).
Future<WalletSync> syncWallet({
  required String mnemonic,
  required String esploraUrl,
}) => RustLib.instance.api.crateApiSyncWallet(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
);

/// A receive address together with the derivation index it came from.
class AddressInfo {
  final String address;
  final int index;

  const AddressInfo({required this.address, required this.index});

  @override
  int get hashCode => address.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          index == other.index;
}

/// A per-asset balance: the asset id (hex) and the amount in atoms (a string to
/// avoid any integer-precision loss across the FFI boundary).
class AssetBalance {
  final String assetId;
  final String atoms;

  const AssetBalance({required this.assetId, required this.atoms});

  @override
  int get hashCode => assetId.hashCode ^ atoms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AssetBalance &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          atoms == other.atoms;
}

/// A snapshot of the wallet after a full scan against an esplora backend.
class WalletSync {
  final int tipHeight;
  final String tipHash;
  final List<AssetBalance> balances;
  final int nextIndex;

  const WalletSync({
    required this.tipHeight,
    required this.tipHash,
    required this.balances,
    required this.nextIndex,
  });

  @override
  int get hashCode =>
      tipHeight.hashCode ^
      tipHash.hashCode ^
      balances.hashCode ^
      nextIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletSync &&
          runtimeType == other.runtimeType &&
          tipHeight == other.tipHeight &&
          tipHash == other.tipHash &&
          balances == other.balances &&
          nextIndex == other.nextIndex;
}
