// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/signer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NoiseSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SeqlnSignerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  NoiseSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    dynamic raw,
  );

  @protected
  SeqlnSigner
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    dynamic raw,
  );

  @protected
  NoiseSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    dynamic raw,
  );

  @protected
  SeqlnSigner
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    dynamic raw,
  );

  @protected
  NoiseSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    dynamic raw,
  );

  @protected
  SeqlnSigner
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressInfo dco_decode_address_info(dynamic raw);

  @protected
  AnchorEvidence dco_decode_anchor_evidence(dynamic raw);

  @protected
  AssetBalance dco_decode_asset_balance(dynamic raw);

  @protected
  AssetDelta dco_decode_asset_delta(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  FeeAsset dco_decode_box_autoadd_fee_asset(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BtcBalance dco_decode_btc_balance(dynamic raw);

  @protected
  BtcFunding dco_decode_btc_funding(dynamic raw);

  @protected
  BtcHtlcInfo dco_decode_btc_htlc_info(dynamic raw);

  @protected
  BtcTx dco_decode_btc_tx(dynamic raw);

  @protected
  BuiltRawTx dco_decode_built_raw_tx(dynamic raw);

  @protected
  ConfidentialReceive dco_decode_confidential_receive(dynamic raw);

  @protected
  CovenantMakerAddress dco_decode_covenant_maker_address(dynamic raw);

  @protected
  CovenantPrepared dco_decode_covenant_prepared(dynamic raw);

  @protected
  EnclaveDecodedInput dco_decode_enclave_decoded_input(dynamic raw);

  @protected
  EnclaveDecodedOutput dco_decode_enclave_decoded_output(dynamic raw);

  @protected
  EnclavePrevout dco_decode_enclave_prevout(dynamic raw);

  @protected
  EnclaveSpendEffects dco_decode_enclave_spend_effects(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FeeAsset dco_decode_fee_asset(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AssetBalance> dco_decode_list_asset_balance(dynamic raw);

  @protected
  List<AssetDelta> dco_decode_list_asset_delta(dynamic raw);

  @protected
  List<EnclaveDecodedInput> dco_decode_list_enclave_decoded_input(dynamic raw);

  @protected
  List<EnclaveDecodedOutput> dco_decode_list_enclave_decoded_output(
    dynamic raw,
  );

  @protected
  List<EnclavePrevout> dco_decode_list_enclave_prevout(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Recipient> dco_decode_list_recipient(dynamic raw);

  @protected
  List<TxRow> dco_decode_list_tx_row(dynamic raw);

  @protected
  LnNodeKeys dco_decode_ln_node_keys(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  FeeAsset? dco_decode_opt_box_autoadd_fee_asset(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PsetFee dco_decode_pset_fee(dynamic raw);

  @protected
  Recipient dco_decode_recipient(dynamic raw);

  @protected
  SeqHtlcInfo dco_decode_seq_htlc_info(dynamic raw);

  @protected
  SeqdexSwapRequestOut dco_decode_seqdex_swap_request_out(dynamic raw);

  @protected
  TxRow dco_decode_tx_row(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletSync dco_decode_wallet_sync(dynamic raw);

  @protected
  XchainSecret dco_decode_xchain_secret(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  NoiseSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    SseDeserializer deserializer,
  );

  @protected
  SeqlnSigner
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    SseDeserializer deserializer,
  );

  @protected
  NoiseSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    SseDeserializer deserializer,
  );

  @protected
  SeqlnSigner
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    SseDeserializer deserializer,
  );

  @protected
  NoiseSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    SseDeserializer deserializer,
  );

  @protected
  SeqlnSigner
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressInfo sse_decode_address_info(SseDeserializer deserializer);

  @protected
  AnchorEvidence sse_decode_anchor_evidence(SseDeserializer deserializer);

  @protected
  AssetBalance sse_decode_asset_balance(SseDeserializer deserializer);

  @protected
  AssetDelta sse_decode_asset_delta(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  FeeAsset sse_decode_box_autoadd_fee_asset(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BtcBalance sse_decode_btc_balance(SseDeserializer deserializer);

  @protected
  BtcFunding sse_decode_btc_funding(SseDeserializer deserializer);

  @protected
  BtcHtlcInfo sse_decode_btc_htlc_info(SseDeserializer deserializer);

  @protected
  BtcTx sse_decode_btc_tx(SseDeserializer deserializer);

  @protected
  BuiltRawTx sse_decode_built_raw_tx(SseDeserializer deserializer);

  @protected
  ConfidentialReceive sse_decode_confidential_receive(
    SseDeserializer deserializer,
  );

  @protected
  CovenantMakerAddress sse_decode_covenant_maker_address(
    SseDeserializer deserializer,
  );

  @protected
  CovenantPrepared sse_decode_covenant_prepared(SseDeserializer deserializer);

  @protected
  EnclaveDecodedInput sse_decode_enclave_decoded_input(
    SseDeserializer deserializer,
  );

  @protected
  EnclaveDecodedOutput sse_decode_enclave_decoded_output(
    SseDeserializer deserializer,
  );

  @protected
  EnclavePrevout sse_decode_enclave_prevout(SseDeserializer deserializer);

  @protected
  EnclaveSpendEffects sse_decode_enclave_spend_effects(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FeeAsset sse_decode_fee_asset(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AssetBalance> sse_decode_list_asset_balance(
    SseDeserializer deserializer,
  );

  @protected
  List<AssetDelta> sse_decode_list_asset_delta(SseDeserializer deserializer);

  @protected
  List<EnclaveDecodedInput> sse_decode_list_enclave_decoded_input(
    SseDeserializer deserializer,
  );

  @protected
  List<EnclaveDecodedOutput> sse_decode_list_enclave_decoded_output(
    SseDeserializer deserializer,
  );

  @protected
  List<EnclavePrevout> sse_decode_list_enclave_prevout(
    SseDeserializer deserializer,
  );

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Recipient> sse_decode_list_recipient(SseDeserializer deserializer);

  @protected
  List<TxRow> sse_decode_list_tx_row(SseDeserializer deserializer);

  @protected
  LnNodeKeys sse_decode_ln_node_keys(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  FeeAsset? sse_decode_opt_box_autoadd_fee_asset(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PsetFee sse_decode_pset_fee(SseDeserializer deserializer);

  @protected
  Recipient sse_decode_recipient(SseDeserializer deserializer);

  @protected
  SeqHtlcInfo sse_decode_seq_htlc_info(SseDeserializer deserializer);

  @protected
  SeqdexSwapRequestOut sse_decode_seqdex_swap_request_out(
    SseDeserializer deserializer,
  );

  @protected
  TxRow sse_decode_tx_row(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletSync sse_decode_wallet_sync(SseDeserializer deserializer);

  @protected
  XchainSecret sse_decode_xchain_secret(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    NoiseSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    SeqlnSigner self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    NoiseSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    SeqlnSigner self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    NoiseSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    SeqlnSigner self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_info(AddressInfo self, SseSerializer serializer);

  @protected
  void sse_encode_anchor_evidence(
    AnchorEvidence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_asset_balance(AssetBalance self, SseSerializer serializer);

  @protected
  void sse_encode_asset_delta(AssetDelta self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fee_asset(
    FeeAsset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_btc_balance(BtcBalance self, SseSerializer serializer);

  @protected
  void sse_encode_btc_funding(BtcFunding self, SseSerializer serializer);

  @protected
  void sse_encode_btc_htlc_info(BtcHtlcInfo self, SseSerializer serializer);

  @protected
  void sse_encode_btc_tx(BtcTx self, SseSerializer serializer);

  @protected
  void sse_encode_built_raw_tx(BuiltRawTx self, SseSerializer serializer);

  @protected
  void sse_encode_confidential_receive(
    ConfidentialReceive self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_covenant_maker_address(
    CovenantMakerAddress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_covenant_prepared(
    CovenantPrepared self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_enclave_decoded_input(
    EnclaveDecodedInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_enclave_decoded_output(
    EnclaveDecodedOutput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_enclave_prevout(
    EnclavePrevout self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_enclave_spend_effects(
    EnclaveSpendEffects self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fee_asset(FeeAsset self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_asset_balance(
    List<AssetBalance> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_asset_delta(
    List<AssetDelta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_enclave_decoded_input(
    List<EnclaveDecodedInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_enclave_decoded_output(
    List<EnclaveDecodedOutput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_enclave_prevout(
    List<EnclavePrevout> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recipient(
    List<Recipient> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tx_row(List<TxRow> self, SseSerializer serializer);

  @protected
  void sse_encode_ln_node_keys(LnNodeKeys self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_fee_asset(
    FeeAsset? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pset_fee(PsetFee self, SseSerializer serializer);

  @protected
  void sse_encode_recipient(Recipient self, SseSerializer serializer);

  @protected
  void sse_encode_seq_htlc_info(SeqHtlcInfo self, SseSerializer serializer);

  @protected
  void sse_encode_seqdex_swap_request_out(
    SeqdexSwapRequestOut self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tx_row(TxRow self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_sync(WalletSync self, SseSerializer serializer);

  @protected
  void sse_encode_xchain_secret(XchainSecret self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNoiseSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSeqlnSigner(
    int ptr,
  );
}
