// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `asset`, `hexenc`, `outpoint_str`, `outpoint`, `rerr`, `script`, `settings`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DecisionDto`, `OwnedOutputDto`, `QuoteDto`, `RewardBatchDto`, `SettingsDto`, `StakingKeyDto`, `StakingRewardDto`, `TxFactsDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Every staking reward in `txs_json`, newest first, as JSON.
///
/// The two shapes attribution recognises are the two ways the consensus rules
/// pay a staker: a coinbase output the wallet owns, and an output paid to
/// `P2WPKH(controller)` by a pool's claim.
Future<String> attributeStakingRewards({
  required String txsJson,
  required String stakingKeysJson,
  required int tipHeight,
  required int coinbaseMaturity,
}) => RustLib.instance.api.crateApiRewardsAttributeStakingRewards(
  txsJson: txsJson,
  stakingKeysJson: stakingKeysJson,
  tipHeight: tipHeight,
  coinbaseMaturity: coinbaseMaturity,
);

/// Group convertible rewards into one batch per asset, skipping the target
/// itself and anything excluded.
///
/// `already_converted_json` is the outpoints a conversion has already committed
/// to -- the whole of the idempotence that stops a restart selling the same
/// reward twice.
Future<String> planRewardBatches({
  required String rewardsJson,
  required String settingsJson,
  required String alreadyConvertedJson,
}) => RustLib.instance.api.crateApiRewardsPlanRewardBatches(
  rewardsJson: rewardsJson,
  settingsJson: settingsJson,
  alreadyConvertedJson: alreadyConvertedJson,
);

/// Whether one batch converts, given what the book is offering.
///
/// `quote_json` is `"null"` when there is no market for the pair, or none deep
/// enough. That is not an error: it is the ordinary state of a young pair, and
/// the batch waits.
Future<String> decideRewardConversion({
  required String batchJson,
  required String quoteJson,
  required String settingsJson,
}) => RustLib.instance.api.crateApiRewardsDecideRewardConversion(
  batchJson: batchJson,
  quoteJson: quoteJson,
  settingsJson: settingsJson,
);

/// How much of a batch a WHOLE-HTLC offer may take.
///
/// The cross-chain rail rests whole offers and the one picked is the smallest
/// that COVERS the request, which can be far larger than the batch. Taking it
/// whole would sell coins staking never paid; selling less is normal, and the
/// remainder waits. Zero means "no fill", never "take everything".
Future<BigInt> rewardSliceForWholeHtlc({
  required BigInt offerAtoms,
  required BigInt batchAtoms,
}) => RustLib.instance.api.crateApiRewardsRewardSliceForWholeHtlc(
  offerAtoms: offerAtoms,
  batchAtoms: batchAtoms,
);

/// Sequentia's coinbase maturity, in blocks -- 1,000, not Bitcoin's 100.
///
/// The protection is a wall-clock one and this chain runs at 60 seconds, so 100
/// blocks here would buy a tenth of what Bitcoin's 100 buys. Exposed so the Dart
/// side never has to hard-code it, and cannot hard-code it wrong: a wallet using
/// 100 calls a reward spendable 900 blocks early and then builds a transaction
/// the chain rejects.
Future<int> sequentiaCoinbaseMaturity() =>
    RustLib.instance.api.crateApiRewardsSequentiaCoinbaseMaturity();

/// The facts attribution needs, gathered from a synced wallet.
///
/// The Dart side has no wollet handle of its own, and it should not: assembling
/// this is exactly the sort of thing that drifts when two languages each do half
/// of it. So the wallet is opened, synced and read here, and Dart receives the
/// same JSON the browser wallets assemble for themselves.
Future<String> walletTxFacts({
  required String mnemonic,
  required String esploraUrl,
}) => RustLib.instance.api.crateApiRewardsWalletTxFacts(
  mnemonic: mnemonic,
  esploraUrl: esploraUrl,
);

/// The staking keys a reward can be paid on, with the `P2WPKH` script that pays
/// them. `delegated` tells `solo` from `lottery`; both are coinbase payments to
/// a staking key, and the difference is whether that key was signing for itself.
Future<String> stakingKeyFacts({
  required String mnemonic,
  required bool delegated,
}) => RustLib.instance.api.crateApiRewardsStakingKeyFacts(
  mnemonic: mnemonic,
  delegated: delegated,
);

/// This wallet's view of the chain tip, which maturity is judged against.
Future<int> tipHeight({required String mnemonic, required String esploraUrl}) =>
    RustLib.instance.api.crateApiRewardsTipHeight(
      mnemonic: mnemonic,
      esploraUrl: esploraUrl,
    );
