// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `arr32`, `arr33`, `asset_path_index`, `bip39_seed`, `derive_hardened`, `hex`, `normalize_phrase`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NoiseInner`

/// Derive the compressed static pubkey (33-byte hex) for a transport static
/// privkey (32 bytes) — the device pubkey a hosted proxy must pin. Handy for a
/// provisioning UI that shows/QRs the device's transport identity.
String devicePubkey({required List<int> staticPrivkey}) => RustLib.instance.api
    .crateApiSignerDevicePubkey(staticPrivkey: staticPrivkey);

/// Derive the device transport (Noise static) private key for the hosted-SeqLN LSP link,
/// deterministically from the wallet mnemonic — the legacy single-node path `m/1017'/0'/0'`
/// (== the asset node's transport key). Kept for back-compat; new callers use
/// [`seqln_derive_node`] / [`seqln_derive_asset`]. Byte-identical to the browser client.
Uint8List seqlnDeviceTransportPrivkey({required String mnemonic}) => RustLib
    .instance
    .api
    .crateApiSignerSeqlnDeviceTransportPrivkey(mnemonic: mnemonic);

/// Derive the device keys for one FIXED hosted node (`"asset"` | `"btc"`) from the wallet
/// mnemonic — the native twin of `seqln-keys.js` `lnDeriveNode`. Role branch selects the key
/// (0' = Noise transport, 1' = SeqLN signing seed); node leaf selects the node (0' =
/// asset/Sequentia, 1' = btc/testnet4):
///   asset transport `m/1017'/0'/0'`   asset signing `m/1017'/1'/0'`
///   btc   transport `m/1017'/0'/1'`   btc   signing `m/1017'/1'/1'`
LnNodeKeys seqlnDeriveNode({required String mnemonic, required String node}) =>
    RustLib.instance.api.crateApiSignerSeqlnDeriveNode(
      mnemonic: mnemonic,
      node: node,
    );

/// Derive the device keys for a PROVISIONED per-asset hosted node from the wallet mnemonic +
/// the 32-byte asset id (hex) — the native twin of `seqln-keys.js` `lnDeriveAsset`. Dedicated
/// branch so it never collides with the fixed asset/btc leaves: transport `m/1017'/2'/<idx>'`,
/// signing `m/1017'/3'/<idx>'`, where `idx = FNV-1a(asset-id) folded to 31 bits`
/// (see [`asset_path_index`]) — so a given asset always re-derives the SAME device identity.
LnNodeKeys seqlnDeriveAsset({
  required String mnemonic,
  required String assetId,
}) => RustLib.instance.api.crateApiSignerSeqlnDeriveAsset(
  mnemonic: mnemonic,
  assetId: assetId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoiseSession>>
abstract class NoiseSession implements RustOpaqueInterface {
  /// Decrypt a body (`len + 16` bytes) into the plaintext message.
  Uint8List decryptBody({required List<int> body});

  /// Decrypt an 18-byte length header, returning the body length that follows
  /// (so the caller knows how many bytes to read next off the socket).
  int decryptHeader({required List<int> hdr});

  /// Encrypt one plaintext message into a full BOLT-8 transport record
  /// (18-byte encrypted length header || encrypted body+MAC).
  Uint8List encrypt({required List<int> msg});

  /// True once the handshake has completed and the transport is live.
  bool isReady();

  /// Begin an initiator handshake toward a hosted proxy whose static pubkey is
  /// `host_static_pubkey` (33 bytes, pinned), using our device transport
  /// static privkey `device_static_privkey` (32 bytes) and a fresh 32-byte
  /// `ephemeral_entropy` the caller draws from the OS RNG.
  static NoiseSession newInitiator({
    required List<int> hostStaticPubkey,
    required List<int> deviceStaticPrivkey,
    required List<int> ephemeralEntropy,
  }) => RustLib.instance.api.crateApiSignerNoiseSessionNewInitiator(
    hostStaticPubkey: hostStaticPubkey,
    deviceStaticPrivkey: deviceStaticPrivkey,
    ephemeralEntropy: ephemeralEntropy,
  );

  /// Consume Act Two (50 bytes) from the responder, returning Act Three (66
  /// bytes) and transitioning to the ready transport. After this call
  /// `encrypt`/`decrypt_header`/`decrypt_body` are live. Errors if the host's
  /// static key does not match the pinned one (host authentication failed).
  Uint8List readActTwo({required List<int> act2});

  /// Produce Act One (50 bytes) to send to the responder.
  Uint8List writeActOne();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SeqlnSigner>>
abstract class SeqlnSigner implements RustOpaqueInterface {
  /// Construct from the raw `hsm_secret` bytes (the on-disk mnemonic form:
  /// `32 zero bytes || mnemonic`). Throws on a malformed / unsupported secret.
  static SeqlnSigner fromHsmSecret({required List<int> hsmSecretBytes}) =>
      RustLib.instance.api.crateApiSignerSeqlnSignerFromHsmSecret(
        hsmSecretBytes: hsmSecretBytes,
      );

  /// Construct from just the BIP-39 mnemonic (no passphrase), synthesizing the
  /// `32 zero bytes || mnemonic` on-disk form. This is the phone's normal
  /// entry point: the wallet already holds the mnemonic in secure storage.
  static SeqlnSigner fromMnemonic({required String mnemonic}) => RustLib
      .instance
      .api
      .crateApiSignerSeqlnSignerFromMnemonic(mnemonic: mnemonic);

  /// The device's compressed node id (33-byte hex). Derived straight from the
  /// mnemonic seed (`HKDF(..,"nodeid")`), so it is available immediately and
  /// matches the id the hosted node reports once it boots over the link.
  String nodeId();

  /// Drive ONE hsmd request -> reply. `frame_bytes` is a single signer-split
  /// frame (`signer_frame.h`: little-endian `u32 len | is_main | node_id? |
  /// dbid | capabilities | hsmd_msg`); the return is the single framed reply
  /// (`u32 len | hsmd_reply`, a zero-length body being the error/reject
  /// sentinel) — byte-for-byte what the native serve loop writes back. Errors
  /// only on a libhsmd-fatal condition (which closes the transport natively).
  Uint8List processFrame({required List<int> frameBytes});

  /// Turn the validating policy on (`enforce`) or off (`permissive`). The
  /// phone has no env, so this is how the caller selects enforce mode (the
  /// device then refuses to sign a commitment that moves funds off-channel).
  void setEnforce({required bool enforce});
}

/// The two device keys for one hosted SeqLN node, derived from the wallet mnemonic —
/// the native twin of the web wallet's `seqln-keys.js`. `transport_privkey` (32 bytes)
/// is the BOLT-8 Noise static privkey (feed to [`device_pubkey`] / [`NoiseSession`]);
/// `signing_seed` (64 lowercase hex) is the opaque string fed to
/// [`SeqlnSigner::from_mnemonic`] — because the hosted node is KEYLESS, this value
/// alone determines its LN identity (node_id + channel keys), so a node's identity +
/// channels survive across sessions and are recoverable from the wallet mnemonic.
class LnNodeKeys {
  final Uint8List transportPrivkey;
  final String signingSeed;

  const LnNodeKeys({required this.transportPrivkey, required this.signingSeed});

  @override
  int get hashCode => transportPrivkey.hashCode ^ signingSeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LnNodeKeys &&
          runtimeType == other.runtimeType &&
          transportPrivkey == other.transportPrivkey &&
          signingSeed == other.signingSeed;
}
