// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `arr32`, `arr33`, `hex`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NoiseInner`

/// Derive the compressed static pubkey (33-byte hex) for a transport static
/// privkey (32 bytes) — the device pubkey a hosted proxy must pin. Handy for a
/// provisioning UI that shows/QRs the device's transport identity.
String devicePubkey({required List<int> staticPrivkey}) => RustLib.instance.api
    .crateApiSignerDevicePubkey(staticPrivkey: staticPrivkey);

/// Derive the device transport (Noise static) private key for the hosted-SeqLN
/// LSP link, deterministically from the wallet mnemonic. This is the native twin
/// of the web wallet's `lnDeviceTransportPriv`: standard BIP39 seed (no
/// passphrase) -> BIP32 `m/1017'/0'/0'` -> the 32-byte private key. It is stable
/// across reinstalls and recoverable from the mnemonic, so the LSP can pin ONE
/// device identity per wallet — and it is byte-identical to the browser client
/// for the same seed (both take the standard BIP39 seed through the same BIP32
/// path), so one hosted LSP can pin the same key whichever client the user runs.
Uint8List seqlnDeviceTransportPrivkey({required String mnemonic}) => RustLib
    .instance
    .api
    .crateApiSignerSeqlnDeviceTransportPrivkey(mnemonic: mnemonic);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NoiseSession>>
abstract class NoiseSession implements RustOpaqueInterface {
  /// Decrypt a body (`len + 16` bytes) into the plaintext message.
  Uint8List decryptBody({required List<int> body});

  /// Decrypt an 18-byte length header, returning the body length that follows
  /// (so the caller knows how many bytes to read next off the socket).
  int decryptHeader({required List<int> hdr});

  /// Encrypt one plaintext message into a full BOLT-8 transport record
  /// (18-byte encrypted length header || encrypted body+MAC).
  Uint8List encrypt({required List<int> msg});

  /// True once the handshake has completed and the transport is live.
  bool isReady();

  /// Begin an initiator handshake toward a hosted proxy whose static pubkey is
  /// `host_static_pubkey` (33 bytes, pinned), using our device transport
  /// static privkey `device_static_privkey` (32 bytes) and a fresh 32-byte
  /// `ephemeral_entropy` the caller draws from the OS RNG.
  static NoiseSession newInitiator({
    required List<int> hostStaticPubkey,
    required List<int> deviceStaticPrivkey,
    required List<int> ephemeralEntropy,
  }) => RustLib.instance.api.crateApiSignerNoiseSessionNewInitiator(
    hostStaticPubkey: hostStaticPubkey,
    deviceStaticPrivkey: deviceStaticPrivkey,
    ephemeralEntropy: ephemeralEntropy,
  );

  /// Consume Act Two (50 bytes) from the responder, returning Act Three (66
  /// bytes) and transitioning to the ready transport. After this call
  /// `encrypt`/`decrypt_header`/`decrypt_body` are live. Errors if the host's
  /// static key does not match the pinned one (host authentication failed).
  Uint8List readActTwo({required List<int> act2});

  /// Produce Act One (50 bytes) to send to the responder.
  Uint8List writeActOne();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SeqlnSigner>>
abstract class SeqlnSigner implements RustOpaqueInterface {
  /// Construct from the raw `hsm_secret` bytes (the on-disk mnemonic form:
  /// `32 zero bytes || mnemonic`). Throws on a malformed / unsupported secret.
  static SeqlnSigner fromHsmSecret({required List<int> hsmSecretBytes}) =>
      RustLib.instance.api.crateApiSignerSeqlnSignerFromHsmSecret(
        hsmSecretBytes: hsmSecretBytes,
      );

  /// Construct from just the BIP-39 mnemonic (no passphrase), synthesizing the
  /// `32 zero bytes || mnemonic` on-disk form. This is the phone's normal
  /// entry point: the wallet already holds the mnemonic in secure storage.
  static SeqlnSigner fromMnemonic({required String mnemonic}) => RustLib
      .instance
      .api
      .crateApiSignerSeqlnSignerFromMnemonic(mnemonic: mnemonic);

  /// The device's compressed node id (33-byte hex). Derived straight from the
  /// mnemonic seed (`HKDF(..,"nodeid")`), so it is available immediately and
  /// matches the id the hosted node reports once it boots over the link.
  String nodeId();

  /// Drive ONE hsmd request -> reply. `frame_bytes` is a single signer-split
  /// frame (`signer_frame.h`: little-endian `u32 len | is_main | node_id? |
  /// dbid | capabilities | hsmd_msg`); the return is the single framed reply
  /// (`u32 len | hsmd_reply`, a zero-length body being the error/reject
  /// sentinel) — byte-for-byte what the native serve loop writes back. Errors
  /// only on a libhsmd-fatal condition (which closes the transport natively).
  Uint8List processFrame({required List<int> frameBytes});

  /// Turn the validating policy on (`enforce`) or off (`permissive`). The
  /// phone has no env, so this is how the caller selects enforce mode (the
  /// device then refuses to sign a commitment that moves funds off-channel).
  void setEnforce({required bool enforce});
}
